### ISSUE TITLE
forced photometry values

### ISSUE THREAD

**Issue by lmorabit** [GabrielaCR/AGNfitter#8]
How are negative forced photometry values handled?  The documentation seems to imply that forced photometry values are handled simply as data but then plotted differently.

**Comment by GabrielaCR** [comment]
The documentation refers only to upper limits, which are plotted differently and treated as data by using 0.5*upp_limit as the data point and +- 0.5*upp_limit as the uncertainties. We do not have any specific treatment of forced photometry. They should be read as normal photometric data for the fitting process.

**Comment by wndywllms** [comment]
I know that if the forced photometry fluxes are negative it will not plot them (this can I think be easily modified), but are they handled as regular fluxes in the fitting (i.e. construction of the likelihoods, etc) ?

**Comment by lmorabit** [comment]
Perhaps then the wiki page should be updated.  It currently reads:

"If a source is non-detected in some bands and you have *forced photometry*
for those, please add columns with non-detection flags to your catalog for
every band (see SETTINGS file, line 64, for detail). In this way, forced
photometry and its error is considered as normal photometry for the
fitting, but the data points are marked differently in the plotting."

(bold text from the page, not mine)

**Comment by GabrielaCR** [comment]
Apologies, you and the wiki are right. The format for **upper-limits** is to have -99 as uncertainty and are used in the computation as I explained above.  In contrast, the **forced photometry** (as Wendy said) are considered regular fluxes in the MCMC fitting process. However, they are not plotted. In the plotting process we are converting the fluxes into luminosities and are not dealing with the negative fluxes yet. Any suggestion or addition to improve upon this point are welcome!
